### ISSUE TITLE
Summary page chart

### ISSUE THREAD

**Issue by johdyn** [johdyn/capstone#10]
## Value statement - a requirement, not a solution
As a **user**
I need **to be able to see my total CO2 emission and emission divided on transport form for periods: Week, month, year**
so that **I have an overview of my CO2 emissions over time**

## Acceptance criteria
- [ ] User can see total emission
- [ ] User can see the division between transport forms in a Pie chart with percentages

## Tasks
- [ ] Create a component which renders a Pie chart that shows car/plane CO2 with percentages and in different colors
- [ ] Component is updated every time a trip item is saved to or removed from local storage

## Size
Large
