### ISSUE TITLE
Add flights to the My Trips page

### ISSUE THREAD

**Issue by johdyn** [johdyn/capstone#7]
## Value statement - a requirement, not a solution
As a user
I need **to be able to add my flights and have a CO2 estimate calculated**
so that I can see my CO2 emission for single flights as well as total CO2 emission

## Acceptance criteria
- [x] When the Add flight form is filled out and sent, the CO2 estimate appears underneath
- [x] When clicking the "add to my trips" button the trip item appears on the My Trips page

## Tasks
- [x] When the add flight form is submitted, the necessary data is send as a flight POST request to the API
- [x] The API returns the CO2 estimate which is added to the Tripitem object together with other data and saved in local storage ("items")
- [x] The Triplist renders the newly added trip item

## Size
medium
