### ISSUE TITLE
Remove trip items from My Trips (local storage)

### ISSUE THREAD

**Issue by johdyn** [johdyn/capstone#8]
## Value statement - a requirement, not a solution
As a **user**
I need **to be able to delete any trip on the My Trips page**
so that **I can remove a trip with wrong details, date or airports which resulted in a wrong CO2 estimate**

## Acceptance criteria
- [ ] When user clicks the bin icon, the trip disappears from the "My Trips" page

## Tasks
- [ ] The item is deleted from local storage by filtering with itemID
- [ ] My Trips page renders again and displays items present in local storage

## Size
medium
