### ISSUE TITLE
Add car trips to the My Trips page

### ISSUE THREAD

**Issue by johdyn** [johdyn/capstone#9]
## Value statement - a requirement, not a solution
As a **user**
I need **to be able to add a car trip with calculated CO2 emission to My Trips**
so that **I can see the CO2 emission for a single trip**

## Acceptance criteria
- [x] The user can add date, distance, vehicle make/model/year to the form
- [x] When the Add flight form is filled out and sent, the CO2 estimate appears underneath
- [x] When clicking the "add to my trips" button the trip item appears on the My Trips page

## Tasks
- [x] User can add distance, vehicle_make, vehicle_model and vehicle year to the form
- [x] The necessary parameters are sent to the API which returns the CO2 estimate
- [x] Determine how vehicle_make/model/year can be implemented in the form before the estimate request is sent?
- [x] Trip item is then added to local storage and renders in My Trips

## Size
large
